# ================================
# 🚀 Script de création d'architecture Flutter (lib/)
# Projet : AutoCentral
# ================================

# Aller dans le dossier lib
Set-Location -Path ".\lib"

# === Dossiers principaux ===
$folders = @(
    "config",
    "core\models",
    "core\services",
    "core\utils",
    "features\auth",
    "features\dashboard",
    "features\vehicles",
    "features\documents",
    "features\settings",
    "widgets",
    "routes"
)

# Créer les dossiers
foreach ($folder in $folders) {
    New-Item -ItemType Directory -Path $folder -Force | Out-Null
}

# === Fichiers principaux ===

# config
New-Item "config\app_config.dart" -ItemType File -Value "// App configuration constants" -Force | Out-Null
New-Item "config\firebase_options.dart" -ItemType File -Value "// Firebase options (auto-generated by FlutterFire CLI)" -Force | Out-Null

# core/models
New-Item "core\models\vehicle.dart" -ItemType File -Value "// Vehicle model" -Force | Out-Null
New-Item "core\models\document.dart" -ItemType File -Value "// Document model" -Force | Out-Null
New-Item "core\models\user.dart" -ItemType File -Value "// User model" -Force | Out-Null

# core/services
New-Item "core\services\auth_service.dart" -ItemType File -Value "// Firebase Auth service" -Force | Out-Null
New-Item "core\services\vehicle_service.dart" -ItemType File -Value "// Firestore vehicle service" -Force | Out-Null
New-Item "core\services\document_service.dart" -ItemType File -Value "// Firestore document service" -Force | Out-Null
New-Item "core\services\notification_service.dart" -ItemType File -Value "// FCM notification service" -Force | Out-Null
New-Item "core\services\api_service.dart" -ItemType File -Value "// (Optionnel) External API service" -Force | Out-Null

# core/utils
New-Item "core\utils\date_helper.dart" -ItemType File -Value "// Date utilities" -Force | Out-Null
New-Item "core\utils\notifications_helper.dart" -ItemType File -Value "// Notifications utilities" -Force | Out-Null
New-Item "core\constants.dart" -ItemType File -Value "// Global constants" -Force | Out-Null

# features/auth
New-Item "features\auth\login_page.dart" -ItemType File -Value "// Login page" -Force | Out-Null
New-Item "features\auth\register_page.dart" -ItemType File -Value "// Register page" -Force | Out-Null
New-Item "features\auth\auth_controller.dart" -ItemType File -Value "// Auth controller" -Force | Out-Null

# features/dashboard
New-Item "features\dashboard\dashboard_page.dart" -ItemType File -Value "// Dashboard page" -Force | Out-Null
New-Item "features\dashboard\dashboard_controller.dart" -ItemType File -Value "// Dashboard controller" -Force | Out-Null

# features/vehicles
New-Item "features\vehicles\vehicle_list_page.dart" -ItemType File -Value "// Vehicle list page" -Force | Out-Null
New-Item "features\vehicles\vehicle_detail_page.dart" -ItemType File -Value "// Vehicle detail page" -Force | Out-Null
New-Item "features\vehicles\vehicle_form_page.dart" -ItemType File -Value "// Vehicle form page" -Force | Out-Null
New-Item "features\vehicles\vehicle_controller.dart" -ItemType File -Value "// Vehicle controller" -Force | Out-Null

# features/documents
New-Item "features\documents\document_list_page.dart" -ItemType File -Value "// Document list page" -Force | Out-Null
New-Item "features\documents\document_detail_page.dart" -ItemType File -Value "// Document detail page" -Force | Out-Null
New-Item "features\documents\document_form_page.dart" -ItemType File -Value "// Document form page" -Force | Out-Null
New-Item "features\documents\document_controller.dart" -ItemType File -Value "// Document controller" -Force | Out-Null

# features/settings
New-Item "features\settings\settings_page.dart" -ItemType File -Value "// Settings page" -Force | Out-Null
New-Item "features\settings\profile_page.dart" -ItemType File -Value "// Profile page" -Force | Out-Null

# widgets
New-Item "widgets\custom_button.dart" -ItemType File -Value "// Custom button widget" -Force | Out-Null
New-Item "widgets\vehicle_card.dart" -ItemType File -Value "// Vehicle card widget" -Force | Out-Null
New-Item "widgets\document_card.dart" -ItemType File -Value "// Document card widget" -Force | Out-Null

# routes
New-Item "routes\app_routes.dart" -ItemType File -Value "// Navigation routes" -Force | Out-Null

Write-Host "✅ Structure du dossier lib/ créée avec succès !"
