// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class UserDetails;

@interface UserDetails : NSObject
+ (instancetype)makeWithUid:(nullable NSString *)uid
    email:(nullable NSString *)email
    displayName:(nullable NSString *)displayName
    photoUrl:(nullable NSString *)photoUrl;
@property(nonatomic, copy, nullable) NSString * uid;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * displayName;
@property(nonatomic, copy, nullable) NSString * photoUrl;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetUserApiCodec(void);

@protocol UserHostApi
/// @return `nil` only when `error != nil`.
- (nullable UserDetails *)getProfileWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setCurrentUserUser:(UserDetails *)user error:(FlutterError *_Nullable *_Nonnull)error;
- (void)clearCurrentUserWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpUserHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UserHostApi> *_Nullable api);

extern void SetUpUserHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UserHostApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
