// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy-SE6QTpy_ZQb8vQ7Vt6diwsKkxuH2yk',
    appId: '1:1085797755521:web:d720858502dfcbd0643b80',
    messagingSenderId: '1085797755521',
    projectId: 'autocentral-free',
    authDomain: 'autocentral-free.firebaseapp.com',
    storageBucket: 'autocentral-free.firebasestorage.app',
    measurementId: 'G-TTH2D6Q95Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwq_9W2ih_CGugA4mR_r2shsN2uk2FcmI',
    appId: '1:1085797755521:android:ab3b5b025a31b738643b80',
    messagingSenderId: '1085797755521',
    projectId: 'autocentral-free',
    storageBucket: 'autocentral-free.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarBAbApT0uVJTgAf5FMObaDdNJfV8bFA',
    appId: '1:1085797755521:ios:c6ea1f7231c1504f643b80',
    messagingSenderId: '1085797755521',
    projectId: 'autocentral-free',
    storageBucket: 'autocentral-free.firebasestorage.app',
    iosBundleId: 'com.example.autocentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDarBAbApT0uVJTgAf5FMObaDdNJfV8bFA',
    appId: '1:1085797755521:ios:c6ea1f7231c1504f643b80',
    messagingSenderId: '1085797755521',
    projectId: 'autocentral-free',
    storageBucket: 'autocentral-free.firebasestorage.app',
    iosBundleId: 'com.example.autocentral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy-SE6QTpy_ZQb8vQ7Vt6diwsKkxuH2yk',
    appId: '1:1085797755521:web:f29c4fe6d4846e0b643b80',
    messagingSenderId: '1085797755521',
    projectId: 'autocentral-free',
    authDomain: 'autocentral-free.firebaseapp.com',
    storageBucket: 'autocentral-free.firebasestorage.app',
    measurementId: 'G-RWR0ZH8MPJ',
  );

}