// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcjNnnEn9qWw4kAU41bleT41rqqin0LuA',
    appId: '1:28999458539:web:7fb9e326d01a2bcad368ae',
    messagingSenderId: '28999458539',
    projectId: 'myautocentral2025',
    authDomain: 'myautocentral2025.firebaseapp.com',
    storageBucket: 'myautocentral2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_sqhQvopSzNYiQQnJTKdb2eitA1uEjlY',
    appId: '1:28999458539:android:ad8bd85a5e541b3cd368ae',
    messagingSenderId: '28999458539',
    projectId: 'myautocentral2025',
    storageBucket: 'myautocentral2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkQWjBodp8ASKl6kX_NcCtx7bxn7B8ivs',
    appId: '1:28999458539:ios:32c762f2cac7a84ad368ae',
    messagingSenderId: '28999458539',
    projectId: 'myautocentral2025',
    storageBucket: 'myautocentral2025.firebasestorage.app',
    iosBundleId: 'com.example.autocentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkQWjBodp8ASKl6kX_NcCtx7bxn7B8ivs',
    appId: '1:28999458539:ios:32c762f2cac7a84ad368ae',
    messagingSenderId: '28999458539',
    projectId: 'myautocentral2025',
    storageBucket: 'myautocentral2025.firebasestorage.app',
    iosBundleId: 'com.example.autocentral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcjNnnEn9qWw4kAU41bleT41rqqin0LuA',
    appId: '1:28999458539:web:3225754cd0d3645cd368ae',
    messagingSenderId: '28999458539',
    projectId: 'myautocentral2025',
    authDomain: 'myautocentral2025.firebaseapp.com',
    storageBucket: 'myautocentral2025.firebasestorage.app',
  );
}
